pipeline {
  agent any

  environment {
    S3_BUCKET = 'your-s3-bucket-name'
    LAMBDA_NAME = 'boilerplate-auth'
    AWS_REGION = 'ap-south-1'
    DEPLOY_PACKAGE = 'target/boilerplate-auth.zip'
  }

  stages {
    stage('Install Dependencies') {
      steps {
        dir('lambda-auth') {
          sh 'npm install'
        }
      }
    }

    stage('Build') {
      steps {
        dir('lambda-auth') {
          script {
            sh 'npm run build'
            sh 'zip -r ${DEPLOY_PACKAGE} .'
          }
        }
      }
    }

    stage('Deploy to S3') {
      steps {
      dir('lambda-auth') {
        withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials-id') {
          s3Upload(
            file: DEPLOY_PACKAGE,
            bucket: "${S3_BUCKET}",
            path: "${LAMBDA_NAME}/${env.BUILD_NUMBER}.zip"
          )
        }
        }
      }
    }

    stage('Update Lambda Function') {
      steps {
        withAWS(region: "${AWS_REGION}", credentials: 'aws-credentials-id') {
          sh """
          aws lambda update-function-code \
            --function-name ${LAMBDA_NAME} \
            --s3-bucket ${S3_BUCKET} \
            --s3-key ${LAMBDA_NAME}/${env.BUILD_NUMBER}.zip
          """
        }
      }
    }
  }
}
